version: '3'
services:
  phpfpm:
    container_name: phpfpm
    image: nanoninja/php-fpm
    #build: .
    ports:
      - 3000:3000
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./App:/var/www/html
    command: php -S="0.0.0.0:3000" -t="/var/www/html"
    depends_on:
      - mysql
    networks:
     - net1

  mysql:
    container_name: mysql
    image: mysql:8
    #command: --default-authentication-plugin=mysql_native_password
    #restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
     - net1
networks:
  net1:
